// <auto-generated />
using BikeListing.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BikeListing.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20210626041518_SeedingData")]
    partial class SeedingData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BikeListing.Data.Bike", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BrandId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Rating")
                        .HasColumnType("float");

                    b.Property<string>("Showroom")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.ToTable("Bikes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BrandId = 1,
                            Name = "Pulsar 150",
                            Rating = 4.2999999999999998,
                            Showroom = "Dindigul"
                        },
                        new
                        {
                            Id = 2,
                            BrandId = 3,
                            Name = "Hornet 2.0",
                            Rating = 4.5,
                            Showroom = "Dindigul"
                        },
                        new
                        {
                            Id = 3,
                            BrandId = 1,
                            Name = "Pulsar NS200",
                            Rating = 3.7000000000000002,
                            Showroom = "Trichy"
                        },
                        new
                        {
                            Id = 4,
                            BrandId = 2,
                            Name = "Xpulse 200T",
                            Rating = 3.7000000000000002,
                            Showroom = "Madurai"
                        });
                });

            modelBuilder.Entity("BikeListing.Data.Brand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SCode")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Brands");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Bajaj",
                            SCode = "BAJ"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Hero",
                            SCode = "HER"
                        },
                        new
                        {
                            Id = 3,
                            Name = "HONDA",
                            SCode = "HON"
                        });
                });

            modelBuilder.Entity("BikeListing.Data.Bike", b =>
                {
                    b.HasOne("BikeListing.Data.Brand", "Brand")
                        .WithMany()
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Brand");
                });
#pragma warning restore 612, 618
        }
    }
}
